name: CI
on:
  push:
    branches: "*"
  pull_request:
    branches: [ master ]
  paths-ignore:
    - README.md
    - LICENSE
    - .gitignore
    - tsconfig.json
    - '.github/**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Test
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh
        export DENO_INSTALL="/home/runner/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"
        ./deno test