name: CI
on:
  pull_request:
    branches: master
  push:
    branches-ignore: master
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Test
      run: |
        ./deno install
        export DENO_INSTALL="/home/runner/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"
        ./deno test