name: Deploy
on:
  push:
    branches: [master, deploy]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build
      run: |
        ./deno install
        ./deno test
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build
      run: |
        ./deno install
        ./deno build
        echo "* @damianperera" > build/CODEOWNERS
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
