name: Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build
      run: |
        ./deno install
        export DENO_INSTALL="/home/runner/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"
        ./deno test
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build
      run: |
        ./deno install
        export DENO_INSTALL="/home/runner/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"
        ./deno build
        echo "* @damianperera" > build/CODEOWNERS
        touch build/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.ADMIN_HOOK }}
        BRANCH: gh-pages
        FOLDER: build
